-- Hyprland 配置（Lua）
-- Hyprland >= 0.55 起 hyprlang 被 Lua 取代。只要本文件存在，hyprland.conf
-- 就会被完全忽略；若本文件不存在，Hyprland 会在每次启动时自动生成一个
-- 示例配置（带 autogenerated 警告）。

hl.config({
  xwayland = {
    force_zero_scaling = true,
  },
})

hl.config({
  misc = {
    vrr = 2,
    font_family = "FiraCode Nerd Font Propo",
    splash_font_family = "FiraCode Nerd Font Propo",
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
  },
})

hl.config({
  input = {
    kb_layout = "us",
    follow_mouse = 1,
    touchpad = {
      natural_scroll = false,
    },
    sensitivity = 0,
    accel_profile = "adaptive",
  },
})

hl.config({
  general = {
    gaps_in = 3,
    gaps_out = 5,
    border_size = 0,
    layout = "dwindle",
  },
})

hl.config({
  decoration = {
    border_part_of_window = false,
    rounding = 11,
    blur = {
      enabled = true,
      xray = true,
    },
    shadow = {
      enabled = false,
    },
  },
})

hl.config({
  animations = {
    enabled = true,
  },
})

hl.curve("easeout", { type = "bezier", points = { { 0.3, 0.7 }, { 0, 1 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "easeout", style = "gnomed" })
hl.animation({ leaf = "layers", enabled = true, speed = 7, bezier = "easeout", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 7, bezier = "easeout", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 7, bezier = "easeout", style = "fade" })

require("sources/env")
require("sources/exec")
require("sources/rule")
require("sources/bind")

-- 每主机模板：显示器布局、工作区绑定、eww 开关
require(os.getenv("HOME") .. "/.config/templates/hyprland.lua")
