[pyprland]

plugins = [
  "expose",
  "magnify",
  # "monitor",
  "shortcuts_menu",
  # "system_notifier",
  "toggle_dpms", # if any screen is powered on, turn them all off, else turn them all on
]

[expose]
include_special = false

[layout_center]
on_new_client = "close"
margin = 0

[shortcuts_menu.entries]
"Window" = "rofi -show window"
"Drun" = "rofi -show drun"
"SSH" = "rofi -show ssh"